export function localUse() {
  return {
    user: {
      id: "user_2p1q8RyieVLpxtD6VSSYOIba8So",
      pathRoot: "/me",
      externalId: null,
      username: null,
      emailAddresses: [
        {
          id: "idn_2p1q8X1b0e9uQOlanKNgzV7mUhU",
          pathRoot: "/me/email_addresses",
          emailAddress: "iamdk353@gmail.com",
          linkedTo: [
            {
              id: "idn_2p1q8VJgnNirMTtzrqxd4K7E0JI",
              pathRoot: "",
              type: "oauth_google",
            },
          ],
          verification: {
            pathRoot: "",
            status: "verified",
            strategy: "from_oauth_google",
            nonce: null,
            message: null,
            externalVerificationRedirectURL: null,
            attempts: null,
            expireAt: "2024-11-18T16:18:09.930Z",
            error: null,
          },
        },
      ],
      phoneNumbers: [],
      web3Wallets: [],
      externalAccounts: [
        {
          id: "eac_2p1q8XB0tbzE8E8kceThJmUzu65",
          pathRoot: "/me/external_accounts",
          identificationId: "idn_2p1q8VJgnNirMTtzrqxd4K7E0JI",
          provider: "google",
          providerUserId: "106132047168987997679",
          emailAddress: "iamdk353@gmail.com",
          approvedScopes:
            "email https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile openid profile",
          firstName: "Dhanush",
          lastName: "Kumar",
          imageUrl:
            "https://img.clerk.com/eyJ0eXBlIjoicHJveHkiLCJzcmMiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQ2c4b2NJOUZjU04xNUZUamduUXo1U1dDQVJJZC1JRjdPajljVGRWSTQ2bXRkcWkxX214aGc9czEwMDAtYyIsInMiOiJGdjdwcHFPUGV2bGtSQkUzbXFRbzZmQnNqTS9PdzZ3a21KYUx1UnBOWnhvIn0",
          username: null,
          publicMetadata: {},
          label: null,
          verification: {
            pathRoot: "",
            status: "verified",
            strategy: "oauth_google",
            nonce: null,
            message: null,
            externalVerificationRedirectURL: null,
            attempts: null,
            expireAt: "2024-11-18T15:39:25.812Z",
            error: {
              code: "external_account_missing_refresh_token",
              message: "Missing refresh token",
              longMessage:
                "We cannot refresh your OAuth access token because the server didn't provide a refresh token. Please re-connect your account.",
              meta: {},
            },
          },
        },
      ],
      enterpriseAccounts: [],
      passkeys: [],
      samlAccounts: [],
      organizationMemberships: [],
      passwordEnabled: false,
      firstName: "Dhanush",
      lastName: "Kumar",
      fullName: "Dhanush Kumar",
      primaryEmailAddressId: "idn_2p1q8X1b0e9uQOlanKNgzV7mUhU",
      primaryEmailAddress: {
        id: "idn_2p1q8X1b0e9uQOlanKNgzV7mUhU",
        pathRoot: "/me/email_addresses",
        emailAddress: "iamdk353@gmail.com",
        linkedTo: [
          {
            id: "idn_2p1q8VJgnNirMTtzrqxd4K7E0JI",
            pathRoot: "",
            type: "oauth_google",
          },
        ],
        verification: {
          pathRoot: "",
          status: "verified",
          strategy: "from_oauth_google",
          nonce: null,
          message: null,
          externalVerificationRedirectURL: null,
          attempts: null,
          expireAt: "2024-11-18T16:18:09.930Z",
          error: null,
        },
      },
      primaryPhoneNumberId: null,
      primaryPhoneNumber: null,
      primaryWeb3WalletId: null,
      primaryWeb3Wallet: null,
      imageUrl:
        "https://img.clerk.com/eyJ0eXBlIjoicHJveHkiLCJzcmMiOiJodHRwczovL2ltYWdlcy5jbGVyay5kZXYvb2F1dGhfZ29vZ2xlL2ltZ18ycDFxOFJCODBwYWJXNVBrZXEyTWtNUHRlNkYifQ",
      hasImage: true,
      twoFactorEnabled: false,
      totpEnabled: false,
      backupCodeEnabled: false,
      publicMetadata: {},
      unsafeMetadata: {},
      createOrganizationEnabled: true,
      deleteSelfEnabled: true,
      lastSignInAt: "2024-11-18T15:52:33.252Z",
      legalAcceptedAt: null,
      updatedAt: "2024-11-18T15:52:33.282Z",
      createdAt: "2024-11-18T15:29:29.781Z",
      cachedSessionsWithActivities: null,
    },
    isLoaded: true,
    isSignedIn: true,
  };
}
