export const vegetables = [
  "Potatoes",
  "Tomatoes",
  "Onions",
  "Garlic",
  "Carrots",
  "Spinach",
  "Lettuce",
  "Broccoli",
  "Cabbage",
  "Cauliflower",
  "Peppers",
  "Cucumbers",
  "Zucchini",
  "Pumpkin",
  "Eggplant",
  "Sweet Potatoes",
  "Radishes",
  "Turnips",
  "Beets",
  "Mushrooms",
  "Leeks",
  "Shallots",
  "Chilies",
  "Green Beans",
  "Peas",
  "Corn",
  "Kale",
  "Swiss Chard",
  "Brussels Sprouts",
  "Asparagus",
  "Okra",
  "Celery",
  "Scallions",
  "Fennel",
  "Parsnips",
  "Rutabaga",
  "Bok Choy",
  "Butternut Squash",
  "Acorn Squash",
  "Spaghetti Squash",
  "Artichokes",
  "Arugula",
  "Dandelion Greens",
  "Collard Greens",
  "Mustard Greens",
  "Watercress",
  "Endive",
  "Chicory",
  "Bell Peppers",
  "Jalapeños",
  "Habaneros",
  "Poblano Peppers",
  "Serrano Peppers",
  "Yellow Squash",
  "Pattypan Squash",
  "Tomatillos",
  "Daikon Radish",
  "Horseradish",
  "Ginger",
  "Turmeric",
  "Yams",
  "Cassava",
  "Taro",
  "Bamboo Shoots",
  "Lotus Root",
  "Tatsoi",
  "Choy Sum",
  "Gai Lan",
  "Snow Peas",
  "Snap Peas",
  "Fiddlehead Ferns",
  "Chili Peppers",
  "Purslane",
  "Napa Cabbage",
  "Savoy Cabbage",
  "Red Cabbage",
  "Purple Carrots",
  "Rainbow Chard",
  "Jerusalem Artichokes",
  "Jicama",
  "Sorrel",
  "Amaranth Leaves",
  "Mizuna",
  "Moringa",
  "Lamb’s Lettuce",
  "Cress",
  "Pigeon Peas",
  "Chayote",
  "Malabar Spinach",
  "Romanesco",
  "Pak Choi",
  "Fava Beans",
  "Broad Beans",
  "Chinese Broccoli",
  "Garlic Scapes",
  "Sprouts",
  "Microgreens",
  "Water Spinach",
  "Winter Melon",
  "Kohlrabi",
  "Pepperoncini",
  "Green Onions",
  "Shallots",
  "Chard",
  "Celeriac",
  "Black Radish",
  "White Radish",
  "Burdock Root",
  "Broccolini",
  "Rapini",
  "Seaweed",
  "Nori",
  "Wakame",
  "Kombu",
  "Hijiki",
  "Alfalfa Sprouts",
  "Bean Sprouts",
  "Mung Bean Sprouts",
  "Soybean Sprouts",
  "Lentil Sprouts",
  "Chickpea Sprouts",
  "Pea Shoots",
  "Fenugreek Sprouts",
  "Radish Sprouts",
  "Broccoli Sprouts",
  "Mustard Sprouts",
  "Sunflower Sprouts",
  "Beet Greens",
  "Carrot Greens",
  "Dill",
  "Parsley",
  "Cilantro",
  "Basil",
  "Mint",
  "Rosemary",
  "Thyme",
  "Sage",
  "Oregano",
  "Tarragon",
  "Chervil",
  "Lavender",
  "Lemongrass",
  "Galangal",
  "Curry Leaves",
  "Bay Leaves",
  "Chicory Greens",
  "Escarole",
  "Radicchio",
  "Frisée",
  "Mizuna",
  "Komatsuna",
  "Mibuna",
  "Shungiku",
  "Methi",
  "Ajwain Leaves",
  "Pandan Leaves",
  "Drumstick Leaves",
  "Snake Beans",
  "Hyacinth Beans",
  "Winged Beans",
  "Yardlong Beans",
  "Tepary Beans",
  "Chickpeas",
  "Lupin Beans",
  "Butter Beans",
  "Black Beans",
  "Adzuki Beans",
  "Soybeans",
  "Lentils",
  "Broad Beans",
  "Runner Beans",
  "Scarlet Runner Beans",
  "White Beans",
  "Pink Beans",
  "Navy Beans",
  "Kidney Beans",
  "Pinto Beans",
  "Cannellini Beans",
  "Borlotti Beans",
  "Cranberry Beans",
  "Roman Beans",
  "Black-eyed Peas",
  "Field Peas",
  "Crowder Peas",
  "Green Gram",
  "Pigeon Peas",
  "Lima Beans",
  "Sword Beans",
  "Sesbania Pods",
  "Cluster Beans",
  "Velvet Beans",
  "Jack Beans",
  "Tindora",
  "Ivy Gourd",
  "Bitter Melon",
  "Cucumber Melon",
  "Armenian Cucumber",
  "Luffa",
  "Sponge Gourd",
  "Bottle Gourd",
  "Snake Gourd",
  "Ash Gourd",
  "Apple Gourd",
];
